<div class="well sidebar-nav cen-sidebar">
<ul class="nav nav-list">
  <li class="nav-header">Opciones</li>
  <li <?php echo ($opcion == 1) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador'); ?>">Reporte 1</a></li>
  <li <?php echo ($opcion == 2) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte2'); ?>">Reporte 2</a></li>
  <li <?php echo ($opcion == 3) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte3'); ?>">Reporte 3</a></li>
  <li <?php echo ($opcion == 4) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte4'); ?>">Reporte 4</a></li>
  <li <?php echo ($opcion == 5) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte5'); ?>">Reporte 5</a></li>
  <li <?php echo ($opcion == 6) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte6'); ?>">Reporte 6</a></li>
  <li <?php echo ($opcion == 7) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte7'); ?>">Reporte 7</a></li>
  <li <?php echo ($opcion == 8) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte8'); ?>">Reporte 8</a></li>
  <li <?php echo ($opcion == 9) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte9'); ?>">Reporte 9</a></li>
  <li <?php echo ($opcion == 10) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte10'); ?>">Reporte 10</a></li>
  <li <?php echo ($opcion == 11) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte11'); ?>">Reporte 11</a></li>
  <li <?php echo ($opcion == 12) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte12'); ?>">Reporte 12</a></li>
  <li <?php echo ($opcion == 13) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte13'); ?>">Reporte 13</a></li>
  <li <?php echo ($opcion == 14) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte14'); ?>">Reporte 14</a></li>
  <li <?php echo ($opcion == 15) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte15'); ?>">Reporte 15</a></li>
  <li <?php echo ($opcion == 25) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte25'); ?>">Reporte 25</a></li>
  <li <?php echo ($opcion == 26) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte26'); ?>">Reporte 26</a></li>
  <li <?php echo ($opcion == 27) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte27'); ?>">Reporte 27</a></li>
  <li <?php echo ($opcion == 28) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte28'); ?>">Reporte 28</a></li>
  <li <?php echo ($opcion == 29) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte29'); ?>">Reporte 29</a></li>
  <li <?php echo ($opcion == 30) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte30'); ?>">Reporte 30</a></li>
  <li <?php echo ($opcion == 31) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte31'); ?>">Reporte 31</a></li>
  <li <?php echo ($opcion == 32) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte32'); ?>">Reporte 32</a></li>
  <li <?php echo ($opcion == 33) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte33'); ?>">Reporte 33</a></li>
  <li <?php echo ($opcion == 34) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte34'); ?>">Reporte 34</a></li>
  <li <?php echo ($opcion == 35) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte35'); ?>">Reporte 35</a></li>
  <li <?php echo ($opcion == 36) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte36'); ?>">Reporte 36</a></li>
  <li <?php echo ($opcion == 37) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte37'); ?>">Reporte 37</a></li>
  <li <?php echo ($opcion == 38) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte38'); ?>">Reporte 38</a></li>
  <li <?php echo ($opcion == 39) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte39'); ?>">Reporte 39</a></li>
  <li <?php echo ($opcion == 40) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte40'); ?>">Reporte 40</a></li>
  <li <?php echo ($opcion == 41) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte41'); ?>">Reporte 41</a></li>
  <li <?php echo ($opcion == 42) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte42'); ?>">Reporte 42</a></li>
  <li <?php echo ($opcion == 43) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte43'); ?>">Reporte 43</a></li>
  <li <?php echo ($opcion == 44) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte44'); ?>">Reporte 44</a></li>
  <li <?php echo ($opcion == 45) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte45'); ?>">Reporte 45</a></li>
  <li <?php echo ($opcion == 46) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte46'); ?>">Reporte 46</a></li>
  <li <?php echo ($opcion == 49) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte49'); ?>">Reporte 49</a></li>
  <li <?php echo ($opcion == 50) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte50'); ?>">Reporte 50</a></li>
  <li <?php echo ($opcion == 51) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte51'); ?>">Reporte 51</a></li>
  <li <?php echo ($opcion == 53) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte53'); ?>">Reporte 53</a></li>
  <li <?php echo ($opcion == 54) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte54'); ?>">Reporte 54</a></li>
  <li <?php echo ($opcion == 55) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte55'); ?>">Reporte 55</a></li>
  <li <?php echo ($opcion == 56) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte56'); ?>">Reporte 56</a></li>
  <li <?php echo ($opcion == 57) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte57'); ?>">Reporte 57</a></li>
  <li <?php echo ($opcion == 58) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte58'); ?>">Reporte 58</a></li>
  <li <?php echo ($opcion == 59) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte59'); ?>">Reporte 59</a></li>
  <li <?php echo ($opcion == 60) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte60'); ?>">Reporte 60</a></li>
  <li <?php echo ($opcion == 61) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte61'); ?>">Reporte 61</a></li>
  <li <?php echo ($opcion == 62) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte62'); ?>">Reporte 62</a></li>
  <li <?php echo ($opcion == 63) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte63'); ?>">Reporte 63</a></li>
  <li <?php echo ($opcion == 64) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte64'); ?>">Reporte 64</a></li>
  <li <?php echo ($opcion == 65) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte65'); ?>">Reporte 65</a></li>
  <li <?php echo ($opcion == 66) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte66'); ?>">Reporte 66</a></li>
  <li <?php echo ($opcion == 67) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte67'); ?>">Reporte 67</a></li>
  <li <?php echo ($opcion == 70) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte70'); ?>">Reporte 70</a></li>
  <li <?php echo ($opcion == 71) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte71'); ?>">Reporte 71</a></li>
  <li <?php echo ($opcion == 72) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte72'); ?>">Reporte 72</a></li>
  <li <?php echo ($opcion == 73) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte73'); ?>">Reporte 73</a></li>
  <li <?php echo ($opcion == 74) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte74'); ?>">Reporte 74</a></li>
  <li <?php echo ($opcion == 75) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte75'); ?>">Reporte 75</a></li>
  <li <?php echo ($opcion == 76) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte76'); ?>">Reporte 76</a></li>
  <li <?php echo ($opcion == 77) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte77'); ?>">Reporte 77</a></li>
  <li <?php echo ($opcion == 78) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte78'); ?>">Reporte 78</a></li>
  <li <?php echo ($opcion == 79) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte79'); ?>">Reporte 79</a></li>
  <li <?php echo ($opcion == 80) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte80'); ?>">Reporte 80</a></li>
  <li <?php echo ($opcion == 81) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte81'); ?>">Reporte 81</a></li>
  <li <?php echo ($opcion == 82) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte82'); ?>">Reporte 82</a></li>
  <li <?php echo ($opcion == 83) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte83'); ?>">Reporte 83</a></li>
  <li <?php echo ($opcion == 84) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/pescador/reporte84'); ?>">Reporte 84</a></li>
</ul>
</div><!--/.well -->
