<div class="well sidebar-nav cen-sidebar sidebar_hide">
<ul class="nav nav-list">
  
  <?php if(!isset($tipo_acuicultor)){ ?>
  <li class="nav-header nav-header-hide">MENU</li>
  <li <?php echo ($opcion == 100) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor'); ?>">            Reporte 100</a></li>
  <li <?php echo ($opcion == 101) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_101'); ?>">Reporte 101</a></li>
  <li <?php echo ($opcion == 102) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_102'); ?>">Reporte 102</a></li>
  <li <?php echo ($opcion == 103) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_103'); ?>">Reporte 103</a></li>
  <li <?php echo ($opcion == 104) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_104'); ?>">Reporte 104</a></li>
  <li <?php echo ($opcion == 105) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_105'); ?>">Reporte 105</a></li>
  <li <?php echo ($opcion == 106) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_106'); ?>">Reporte 106</a></li>
  <li <?php echo ($opcion == 107) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_107'); ?>">Reporte 107</a></li>
  <li <?php echo ($opcion == 108) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_108'); ?>">Reporte 108</a></li>
  <li <?php echo ($opcion == 109) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_109'); ?>">Reporte 109</a></li>
  <li <?php echo ($opcion == 110) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_110'); ?>">Reporte 110</a></li>
  <li <?php echo ($opcion == 111) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_111'); ?>">Reporte 111</a></li>
  <li <?php echo ($opcion == 112) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_112'); ?>">Reporte 112</a></li>
  <li <?php echo ($opcion == 113) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_113'); ?>">Reporte 113</a></li>
  <li <?php echo ($opcion == 114) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_114'); ?>">Reporte 114</a></li>
  <li <?php echo ($opcion == 115) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_115'); ?>">Reporte 115</a></li>
  <li <?php echo ($opcion == 116) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_116'); ?>">Reporte 116</a></li>
  <li <?php echo ($opcion == 117) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_117'); ?>">Reporte 117</a></li>
  <li <?php echo ($opcion == 118) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_118'); ?>">Reporte 118</a></li>
  <li <?php echo ($opcion == 119) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_119'); ?>">Reporte 119</a></li>
  <li <?php echo ($opcion == 120) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_120'); ?>">Reporte 120</a></li>
  <li <?php echo ($opcion == 121) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_121'); ?>">Reporte 121</a></li>
  <li <?php echo ($opcion == 122) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_122'); ?>">Reporte 122</a></li>
  <li <?php echo ($opcion == 123) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_123'); ?>">Reporte 123</a></li>
  <li <?php echo ($opcion == 124) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_124'); ?>">Reporte 124</a></li>
  <li <?php echo ($opcion == 125) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_125'); ?>">Reporte 125</a></li>
  <li <?php echo ($opcion == 126) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_126'); ?>">Reporte 126</a></li>
  <li <?php echo ($opcion == 127) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_127'); ?>">Reporte 127</a></li>
  <li <?php echo ($opcion == 128) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_128'); ?>">Reporte 128</a></li>
  <li <?php echo ($opcion == 129) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_129'); ?>">Reporte 129</a></li>
  <li <?php echo ($opcion == 130) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_130'); ?>">Reporte 130</a></li>
  <li <?php echo ($opcion == 131) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_131'); ?>">Reporte 131</a></li>
  <li <?php echo ($opcion == 132) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_132'); ?>">Reporte 132</a></li>
  <li <?php echo ($opcion == 133) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_133'); ?>">Reporte 133</a></li>
  <li <?php echo ($opcion == 134) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_134'); ?>">Reporte 134</a></li>
  <li <?php echo ($opcion == 135) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_135'); ?>">Reporte 135</a></li>
  <li <?php echo ($opcion == 136) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_136'); ?>">Reporte 136</a></li>
  <li <?php echo ($opcion == 137) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_137'); ?>">Reporte 137</a></li>
  <li <?php echo ($opcion == 138) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_138'); ?>">Reporte 138</a></li>
  <li <?php echo ($opcion == 139) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_139'); ?>">Reporte 139</a></li>
  <li <?php echo ($opcion == 140) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_140'); ?>">Reporte 140</a></li>
  <li <?php echo ($opcion == 141) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_141'); ?>">Reporte 141</a></li>
  <li <?php echo ($opcion == 142) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_142'); ?>">Reporte 142</a></li>
  <li <?php echo ($opcion == 143) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_143'); ?>">Reporte 143</a></li>
  <li <?php echo ($opcion == 144) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_144'); ?>">Reporte 144</a></li>
  <li <?php echo ($opcion == 145) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_145'); ?>">Reporte 145</a></li>
  <li <?php echo ($opcion == 146) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_146'); ?>">Reporte 146</a></li>
  <li <?php echo ($opcion == 147) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_147'); ?>">Reporte 147</a></li>
  <li <?php echo ($opcion == 148) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_147'); ?>">Reporte 148</a></li>
  <li <?php echo ($opcion == 149) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_149'); ?>">Reporte 149</a></li>
  <li <?php echo ($opcion == 150) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_150'); ?>">Reporte 150</a></li>
  <li <?php echo ($opcion == 151) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_151'); ?>">Reporte 151</a></li>
  <li <?php echo ($opcion == 152) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_152'); ?>">Reporte 152</a></li>
  <li <?php echo ($opcion == 153) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_153'); ?>">Reporte 153</a></li>
  <li <?php echo ($opcion == 154) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_154'); ?>">Reporte 154</a></li>
  <li <?php echo ($opcion == 155) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_155'); ?>">Reporte 155</a></li>
  <li <?php echo ($opcion == 156) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_156'); ?>">Reporte 156</a></li>
  <li <?php echo ($opcion == 157) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_157'); ?>">Reporte 157</a></li>
  <li <?php echo ($opcion == 158) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_158'); ?>">Reporte 158</a></li>
  <li <?php echo ($opcion == 159) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_159'); ?>">Reporte 159</a></li>
  <li <?php echo ($opcion == 160) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_160'); ?>">Reporte 160</a></li>
  <li <?php echo ($opcion == 161) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_161'); ?>">Reporte 161</a></li>
  <li <?php echo ($opcion == 162) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_162'); ?>">Reporte 162</a></li>
  <li <?php echo ($opcion == 163) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_162'); ?>">Reporte 163</a></li>
  <li <?php echo ($opcion == 164) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_164'); ?>">Reporte 164</a></li>
  <li <?php echo ($opcion == 165) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_165'); ?>">Reporte 165</a></li>
  <li <?php echo ($opcion == 166) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_166'); ?>">Reporte 166</a></li>
  <li <?php echo ($opcion == 167) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_167'); ?>">Reporte 167</a></li>
  <li <?php echo ($opcion == 168) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_168'); ?>">Reporte 168</a></li>
  <li <?php echo ($opcion == 169) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_169'); ?>">Reporte 169</a></li>
  <li <?php echo ($opcion == 170) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_170'); ?>">Reporte 170</a></li>
  <li <?php echo ($opcion == 171) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_171'); ?>">Reporte 171</a></li>
  <li <?php echo ($opcion == 172) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_172'); ?>">Reporte 172</a></li>
  <li <?php echo ($opcion == 173) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_173'); ?>">Reporte 173</a></li>
  <li <?php echo ($opcion == 174) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_174'); ?>">Reporte 174</a></li>
  <li <?php echo ($opcion == 175) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_175'); ?>">Reporte 175</a></li>
  <li <?php echo ($opcion == 176) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_176'); ?>">Reporte 176</a></li>
  <li <?php echo ($opcion == 177) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_177'); ?>">Reporte 177</a></li>
  <li <?php echo ($opcion == 178) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_178'); ?>">Reporte 178</a></li>
  <li <?php echo ($opcion == 179) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_179'); ?>">Reporte 179</a></li>
  <li <?php echo ($opcion == 180) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_180'); ?>">Reporte 180</a></li>
  <li <?php echo ($opcion == 181) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_181'); ?>">Reporte 181</a></li>
  <li <?php echo ($opcion == 182) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_182'); ?>">Reporte 182</a></li>
  <li <?php echo ($opcion == 183) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_183'); ?>">Reporte 183</a></li>
  <li <?php echo ($opcion == 184) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_184'); ?>">Reporte 184</a></li>
  <li <?php echo ($opcion == 185) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_185'); ?>">Reporte 185</a></li>
  <li <?php echo ($opcion == 186) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_186'); ?>">Reporte 186</a></li>
  <li <?php echo ($opcion == 187) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_187'); ?>">Reporte 187</a></li>
  <li <?php echo ($opcion == 188) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_188'); ?>">Reporte 188</a></li>
  <li <?php echo ($opcion == 189) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_189'); ?>">Reporte 189</a></li>
  <li <?php echo ($opcion == 190) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_190'); ?>">Reporte 190</a></li>
  <li <?php echo ($opcion == 191) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_191'); ?>">Reporte 191</a></li>
  <li <?php echo ($opcion == 192) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_192'); ?>">Reporte 192</a></li>
  <li <?php echo ($opcion == 193) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_193'); ?>">Reporte 193</a></li>
  <li <?php echo ($opcion == 194) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_194'); ?>">Reporte 194</a></li>
  <li <?php echo ($opcion == 195) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_195'); ?>">Reporte 195</a></li>
  <li <?php echo ($opcion == 196) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_196'); ?>">Reporte 196</a></li>
  <li <?php echo ($opcion == 197) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_197'); ?>">Reporte 197</a></li>
  <li <?php echo ($opcion == 198) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_198'); ?>">Reporte 198</a></li>
  <li <?php echo ($opcion == 199) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor/reporte_199'); ?>">Reporte 199</a></li>
  <?php  }elseif ($tipo_acuicultor == 'natural') { ?>
  <li class="nav-header nav-header-hide">MENU </li>
  <li <?php echo ($opcion == 100) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural'); ?>">            Reporte 100</a></li>
  <li <?php echo ($opcion == 135) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_135'); ?>">Reporte 135</a></li>
  <li <?php echo ($opcion == 136) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_136'); ?>">Reporte 136</a></li>
  <li <?php echo ($opcion == 137) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_137'); ?>">Reporte 137</a></li>
  <li <?php echo ($opcion == 138) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_138'); ?>">Reporte 138</a></li>
  <li <?php echo ($opcion == 139) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_139'); ?>">Reporte 139</a></li>
  <li <?php echo ($opcion == 140) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_140'); ?>">Reporte 140</a></li>
  <li <?php echo ($opcion == 141) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_141'); ?>">Reporte 141</a></li>
  <li <?php echo ($opcion == 142) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_142'); ?>">Reporte 142</a></li>
  <li <?php echo ($opcion == 143) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_143'); ?>">Reporte 143</a></li>
  <li <?php echo ($opcion == 144) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_144'); ?>">Reporte 144</a></li>
  <li <?php echo ($opcion == 145) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_145'); ?>">Reporte 145</a></li>
  <li <?php echo ($opcion == 146) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_146'); ?>">Reporte 146</a></li>
  <li <?php echo ($opcion == 147) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_147'); ?>">Reporte 147</a></li>
  <li <?php echo ($opcion == 148) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_147'); ?>">Reporte 148</a></li>
  <li <?php echo ($opcion == 149) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_149'); ?>">Reporte 149</a></li>
  <li <?php echo ($opcion == 150) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_150'); ?>">Reporte 150</a></li>
  <li <?php echo ($opcion == 151) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_151'); ?>">Reporte 151</a></li>
  <li <?php echo ($opcion == 152) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_152'); ?>">Reporte 152</a></li>
  <li <?php echo ($opcion == 153) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_153'); ?>">Reporte 153</a></li>
  <li <?php echo ($opcion == 154) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_154'); ?>">Reporte 154</a></li>
  <li <?php echo ($opcion == 155) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_155'); ?>">Reporte 155</a></li>
  <li <?php echo ($opcion == 156) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_156'); ?>">Reporte 156</a></li>
  <li <?php echo ($opcion == 157) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_157'); ?>">Reporte 157</a></li>
  <li <?php echo ($opcion == 158) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_158'); ?>">Reporte 158</a></li>
  <li <?php echo ($opcion == 159) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_159'); ?>">Reporte 159</a></li>
  <li <?php echo ($opcion == 160) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_160'); ?>">Reporte 160</a></li>
  <li <?php echo ($opcion == 161) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_161'); ?>">Reporte 161</a></li>
  <li <?php echo ($opcion == 162) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_162'); ?>">Reporte 162</a></li>
  <li <?php echo ($opcion == 163) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_162'); ?>">Reporte 163</a></li>
  <li <?php echo ($opcion == 164) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_164'); ?>">Reporte 164</a></li>
  <li <?php echo ($opcion == 165) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_165'); ?>">Reporte 165</a></li>
  <li <?php echo ($opcion == 166) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_166'); ?>">Reporte 166</a></li>
  <li <?php echo ($opcion == 167) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_167'); ?>">Reporte 167</a></li>
  <li <?php echo ($opcion == 168) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_168'); ?>">Reporte 168</a></li>
  <li <?php echo ($opcion == 169) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_169'); ?>">Reporte 169</a></li>
  <li <?php echo ($opcion == 170) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_170'); ?>">Reporte 170</a></li>
  <li <?php echo ($opcion == 171) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_171'); ?>">Reporte 171</a></li>
  <li <?php echo ($opcion == 172) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_172'); ?>">Reporte 172</a></li>
  <li <?php echo ($opcion == 173) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_173'); ?>">Reporte 173</a></li>
  <li <?php echo ($opcion == 174) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_174'); ?>">Reporte 174</a></li>
  <li <?php echo ($opcion == 175) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_175'); ?>">Reporte 175</a></li>
  <li <?php echo ($opcion == 176) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_176'); ?>">Reporte 176</a></li>
  <li <?php echo ($opcion == 177) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_177'); ?>">Reporte 177</a></li>
  <li <?php echo ($opcion == 178) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_178'); ?>">Reporte 178</a></li>
  <li <?php echo ($opcion == 179) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_179'); ?>">Reporte 179</a></li>
  <li <?php echo ($opcion == 180) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_180'); ?>">Reporte 180</a></li>
  <li <?php echo ($opcion == 181) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_181'); ?>">Reporte 181</a></li>
  <li <?php echo ($opcion == 182) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_182'); ?>">Reporte 182</a></li>
  <li <?php echo ($opcion == 183) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_183'); ?>">Reporte 183</a></li>
  <li <?php echo ($opcion == 184) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_184'); ?>">Reporte 184</a></li>
  <li <?php echo ($opcion == 185) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_185'); ?>">Reporte 185</a></li>
  <li <?php echo ($opcion == 186) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_186'); ?>">Reporte 186</a></li>
  <li <?php echo ($opcion == 187) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_187'); ?>">Reporte 187</a></li>
  <li <?php echo ($opcion == 188) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_188'); ?>">Reporte 188</a></li>
  <li <?php echo ($opcion == 189) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_189'); ?>">Reporte 189</a></li>
  <li <?php echo ($opcion == 190) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_190'); ?>">Reporte 190</a></li>
  <li <?php echo ($opcion == 191) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_191'); ?>">Reporte 191</a></li>
  <li <?php echo ($opcion == 192) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_192'); ?>">Reporte 192</a></li>
  <li <?php echo ($opcion == 193) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_193'); ?>">Reporte 193</a></li>
  <li <?php echo ($opcion == 194) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_194'); ?>">Reporte 194</a></li>
  <li <?php echo ($opcion == 195) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_195'); ?>">Reporte 195</a></li>
  <li <?php echo ($opcion == 196) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_196'); ?>">Reporte 196</a></li>
  <li <?php echo ($opcion == 197) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_197'); ?>">Reporte 197</a></li>
  <li <?php echo ($opcion == 198) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_198'); ?>">Reporte 198</a></li>
  <li <?php echo ($opcion == 199) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_natural/reporte_199'); ?>">Reporte 199</a></li>
  <?php  }elseif ($tipo_acuicultor == 'juridica') { ?>
  <li class="nav-header nav-header-hide">MENU </li>
  <li <?php echo ($opcion == 100) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica'); ?>">            Reporte 100</a></li>
  <li <?php echo ($opcion == 135) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_135'); ?>">Reporte 135</a></li>
  <li <?php echo ($opcion == 136) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_136'); ?>">Reporte 136</a></li>
  <li <?php echo ($opcion == 137) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_137'); ?>">Reporte 137</a></li>
  <li <?php echo ($opcion == 138) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_138'); ?>">Reporte 138</a></li>
  <li <?php echo ($opcion == 139) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_139'); ?>">Reporte 139</a></li>
  <li <?php echo ($opcion == 140) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_140'); ?>">Reporte 140</a></li>
  <li <?php echo ($opcion == 141) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_141'); ?>">Reporte 141</a></li>
  <li <?php echo ($opcion == 142) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_142'); ?>">Reporte 142</a></li>
  <li <?php echo ($opcion == 143) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_143'); ?>">Reporte 143</a></li>
  <li <?php echo ($opcion == 144) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_144'); ?>">Reporte 144</a></li>
  <li <?php echo ($opcion == 145) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_145'); ?>">Reporte 145</a></li>
  <li <?php echo ($opcion == 146) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_146'); ?>">Reporte 146</a></li>
  <li <?php echo ($opcion == 147) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_147'); ?>">Reporte 147</a></li>
  <li <?php echo ($opcion == 148) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_147'); ?>">Reporte 148</a></li>
  <li <?php echo ($opcion == 149) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_149'); ?>">Reporte 149</a></li>
  <li <?php echo ($opcion == 150) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_150'); ?>">Reporte 150</a></li>
  <li <?php echo ($opcion == 151) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_151'); ?>">Reporte 151</a></li>
  <li <?php echo ($opcion == 152) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_152'); ?>">Reporte 152</a></li>
  <li <?php echo ($opcion == 153) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_153'); ?>">Reporte 153</a></li>
  <li <?php echo ($opcion == 154) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_154'); ?>">Reporte 154</a></li>
  <li <?php echo ($opcion == 155) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_155'); ?>">Reporte 155</a></li>
  <li <?php echo ($opcion == 156) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_156'); ?>">Reporte 156</a></li>
  <li <?php echo ($opcion == 157) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_157'); ?>">Reporte 157</a></li>
  <li <?php echo ($opcion == 158) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_158'); ?>">Reporte 158</a></li>
  <li <?php echo ($opcion == 159) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_159'); ?>">Reporte 159</a></li>
  <li <?php echo ($opcion == 160) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_160'); ?>">Reporte 160</a></li>
  <li <?php echo ($opcion == 161) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_161'); ?>">Reporte 161</a></li>
  <li <?php echo ($opcion == 162) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_162'); ?>">Reporte 162</a></li>
  <li <?php echo ($opcion == 163) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_162'); ?>">Reporte 163</a></li>
  <li <?php echo ($opcion == 164) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_164'); ?>">Reporte 164</a></li>
  <li <?php echo ($opcion == 165) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_165'); ?>">Reporte 165</a></li>
  <li <?php echo ($opcion == 166) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_166'); ?>">Reporte 166</a></li>
  <li <?php echo ($opcion == 167) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_167'); ?>">Reporte 167</a></li>
  <li <?php echo ($opcion == 168) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_168'); ?>">Reporte 168</a></li>
  <li <?php echo ($opcion == 169) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_169'); ?>">Reporte 169</a></li>
  <li <?php echo ($opcion == 170) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_170'); ?>">Reporte 170</a></li>
  <li <?php echo ($opcion == 171) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_171'); ?>">Reporte 171</a></li>
  <li <?php echo ($opcion == 172) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_172'); ?>">Reporte 172</a></li>
  <li <?php echo ($opcion == 173) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_173'); ?>">Reporte 173</a></li>
  <li <?php echo ($opcion == 174) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_174'); ?>">Reporte 174</a></li>
  <li <?php echo ($opcion == 175) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_175'); ?>">Reporte 175</a></li>
  <li <?php echo ($opcion == 176) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_176'); ?>">Reporte 176</a></li>
  <li <?php echo ($opcion == 177) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_177'); ?>">Reporte 177</a></li>
  <li <?php echo ($opcion == 178) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_178'); ?>">Reporte 178</a></li>
  <li <?php echo ($opcion == 179) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_179'); ?>">Reporte 179</a></li>
  <li <?php echo ($opcion == 180) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_180'); ?>">Reporte 180</a></li>
  <li <?php echo ($opcion == 181) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_181'); ?>">Reporte 181</a></li>
  <li <?php echo ($opcion == 182) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_182'); ?>">Reporte 182</a></li>
  <li <?php echo ($opcion == 183) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_183'); ?>">Reporte 183</a></li>
  <li <?php echo ($opcion == 184) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_184'); ?>">Reporte 184</a></li>
  <li <?php echo ($opcion == 185) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_185'); ?>">Reporte 185</a></li>
  <li <?php echo ($opcion == 186) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_186'); ?>">Reporte 186</a></li>
  <li <?php echo ($opcion == 187) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_187'); ?>">Reporte 187</a></li>
  <li <?php echo ($opcion == 188) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_188'); ?>">Reporte 188</a></li>
  <li <?php echo ($opcion == 189) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_189'); ?>">Reporte 189</a></li>
  <li <?php echo ($opcion == 190) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_190'); ?>">Reporte 190</a></li>
  <li <?php echo ($opcion == 191) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_191'); ?>">Reporte 191</a></li>
  <li <?php echo ($opcion == 192) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_192'); ?>">Reporte 192</a></li>
  <li <?php echo ($opcion == 193) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_193'); ?>">Reporte 193</a></li>
  <li <?php echo ($opcion == 194) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_194'); ?>">Reporte 194</a></li>
  <li <?php echo ($opcion == 195) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_195'); ?>">Reporte 195</a></li>
  <li <?php echo ($opcion == 196) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_196'); ?>">Reporte 196</a></li>
  <li <?php echo ($opcion == 197) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_197'); ?>">Reporte 197</a></li>
  <li <?php echo ($opcion == 198) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_198'); ?>">Reporte 198</a></li>
  <li <?php echo ($opcion == 199) ? 'class="active"' : ''; ?>><a href="<?php echo site_url('tabulados/acuicultor_juridica/reporte_199'); ?>">Reporte 199</a></li>
<?php } ?>


</ul>
</div><!--/.well -->
